# Generated by Django 5.0.4 on 2024-05-11 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nempresa', models.CharField(max_length=60, unique=True, verbose_name='Nombre de la empresa')),
                ('acronimo', models.CharField(blank=True, max_length=60, null=True, verbose_name='Acronimo')),
                ('rif', models.CharField(blank=True, max_length=30, null=True, verbose_name='R.I.F')),
                ('imgref', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Imagen de Referencia')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noficina', models.CharField(max_length=60, unique=True, verbose_name='Nombre de la Oficina')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedemp', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('nEmp', models.CharField(max_length=60, verbose_name='Nombre')),
                ('aEmp', models.CharField(max_length=60, verbose_name='Apellido')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.empresa')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.oficina')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=10, null=True, verbose_name='Cedula')),
                ('avatar', models.ImageField(blank=True, default='users/default.jpg', null=True, upload_to='profiles')),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
